name: CI-Staging
on:
  release:
    types: [prereleased]
permissions: read-all # This is required to read the secrets
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions: read-all # This is required to read the secrets
    steps:
      - name: deploy
        run: |
          URL="${{ secrets.STAGING_DEPLOY_WEBHOOK }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"